---
training_filename: /mnt/data/training/training-20p.libsvm
training_is_binary: false
training_bytes_per_example: 0
testing_filename: /mnt/data/testing/testing.libsvm
testing_is_binary: false
testing_bytes_per_example: 574
num_examples: 10000000
num_testing_examples: 4627840
num_features: 565
positive: 1
max_sample_size: 200000
max_bin_size: 10
min_gamma: 0.0001
default_gamma: 0.25
min_ess: 0.5
num_iterations: 100
max_leaves: 4
max_trials_before_shrink: 1000000
channel_size: 8
buffer_size: 1000000
batch_size: 1000
serial_sampling: false
sampler_num_threads: 1
sampler_init_grid_size: 1.0
sampler_average_window_size: 1000
num_examples_per_block: 40960
disk_buffer_filename: stratified.bin
num_assigners: 1
num_samplers: 3
network: ["3.84.103.203", "54.89.228.82"]
port: 8888
local_name: local_worker
save_process: true
debug_mode: true
models_table_filename: ./models_table.txt
incremental_testing: true
testing_scores_only: false
save_interval: 1
sampling_mode: s3
sampler_scanner: sampler
sleep_duration: 5
